---
title: "Participants, sampling, and recruitment"
resource_files:
- s04.1.Rmd
- css/custom-learnr.css
- images/logo_dark.png
- images/logo.png
runtime: shiny_prerendered
output:
  learnr::tutorial:
    css: css/custom-learnr.css
subtitle: Session 4.1
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

Now that you have a good, evidence-based research question, a well-defined primary outcome, and a rigorous study design, you are ready to think about the subjects of your research. Most often your research subjects—participants—will be people or places. You have two basic questions to answer about these participants: 

1. How will you find, recruit, and select them? (sampling)
2. How many do you need to include to meet your study objectives? (power)

In this session we'll consider strategies to answer the first question—selecting a study sample from a larger target population.

### Learning Objectives

* Devise a sampling strategy to meet study objectives and resources

## Before class

### Prepare

* Read Sections 1.3 and 1.4 of [OpenIntro Statistics](https://www.openintro.org/redirect.php?go=os4_tablet&referrer=/stat/os4.php){target="_blank"}
* Watch [this video on sampling from the DHS](https://youtu.be/DD5npelwh80){target="_blank"}

## During class

[Deck](https://docs.google.com/presentation/d/e/2PACX-1vRVkL1NiTpfdg3Bisqj3ZZ-LHUwBDOM5dbAFMN-t8teCDltUq-5qOZF4TRteQkOBuXgXD5QmkygpZ94/pub?start=false&loop=false&delayms=15000){target="_blank"}

### Activity

In the first activity you'll learn more about how multi-stage cluster sampling surveys like the DHS are planned and conducted. In the second activity, you’ll examine the complete count 1880 census dataset for North Carolina along with several samples from this population to help you understand sampling error.

Follow [this link](https://learn.themethodsection.com/tutorial/sampling/){target="_blank"} to get started on an activity designed to help you understand sampling error.

<iframe src="https://drive.google.com/file/d/1LEeD0Lk0f3D8zonXddtWa2HjFHTPcc3u/preview" width="100%" height="480"></iframe>

[Download activity sheets](https://drive.google.com/open?id=1VKNGv6buP9iGLPEbrbdYsw1YtcKGNkdE)

## After class

TBA